resource:
  deployment: true
  replicationcontroller: true
  replicaset: true
  daemonset: true
  statefulset: true
  services: true
  pod: true
  job: true
  node: true
  hpa: true
  clusterrole: true
  serviceaccount: true
  persistentvolume: true
  namespace: true
  configmap: false    # disabled because it is a little spammy by default. kube-system configmaps updated a lot
  secret: false       # disabled for security reasons